### ISSUE TITLE
When importing a dataset using the "Import Data" option, the zooming and panning can sometimes not scale properly if the y axes have different scales.

### ISSUE THREAD

**Issue by OCopping** [rosalindfranklininstitute/Chamelogator#10]
E.g. if showing SessionId vs MolecularConc. and import SessionId vs BufferConc., they will have different scales. When attempting to zoom, it doesn't work as expected.

**Comment by dfq16044** [comment]
Using dash instead of js. Should not be an issue anymore. 
A new issue should be opened for new bugs within that framework

**Comment by dfq16044** [comment]
Using dash instead of js. Should not be an issue anymore.
A new issue should be opened for new bugs within that framework
