### ISSUE TITLE
Remove the need for Pandas Dataframes and just use SQLAlchemy's built-in methods for dealing with the data

### ISSUE THREAD

**Issue by OCopping** [rosalindfranklininstitute/Chamelogator#6]
Pandas and its Dataframes might not be needed as SQLAlchemy has its own methods for combining data together (keys and relationships/association proxies).

**Comment by dfq16044** [comment]
Already partially implemented it.
Added relationships to the objects in the Data model.

**Comment by dfq16044** [comment]
Done
